Steppy
vlggms/tegustation-bay12 pull request #11
Opened 2021-06-13 23:04 UTC by retlaw34

## About the Pull Request
How dare you call this tegustation and not include the reptiles?

## Why It's Good For The Game

![image](https://user-images.githubusercontent.com/58402542/121824348-7eba5700-cc60-11eb-9e5a-9ba48427fa9e.png)
![image](https://user-images.githubusercontent.com/58402542/121824357-8ed23680-cc60-11eb-82fb-bbdd0dc0ac49.png)
![image](https://user-images.githubusercontent.com/58402542/121824370-a0b3d980-cc60-11eb-9f43-b47cb3f94255.png)

## Did you test it?

who the fuck needs to test for steppy

## Changelog

:cl:
* bugfix - Steppy works again.
/:cl:

2021-06-13 23:37 UTC, Samuuu3 commented
Steppy I've missed you

2021-06-13 23:49 UTC, retlaw34 commented
steppy my beloved

2021-06-14 07:28 UTC, Cupax3 commented
Squash please

2021-06-14 09:13 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/hostile/retaliate/alligator.dm
> +	new /obj/item/clothing/glasses/hud/security/sunglasses(T)
I suppose hud sunglasses have a different path, so you should search for it and place it here.

2021-06-14 10:25 UTC, Cupax3 commented
@retlaw34 Test your changes locally before, too. Thanks.

2021-06-14 13:57 UTC, Cupax3 requested changes
Test it locally & remove the list tag from the :cl: please, thank you.

EDIT: And squash too, thanks.

2021-06-15 00:58 UTC, closed without merging