Trusted players
vlggms/tegustation-bay12 pull request #120
Opened 2021-10-02 07:49 UTC by EgorDinamit

## About the Pull Request

Adds a "trusted players" system to the codebase.
It is simply a list of ckeys, defined in config, that give them a different OOC color.
I am planning on expanding it, but for now, that's the only thing it grants.

## Why It's Good For The Game

"Trusted Players" was a thing on /tg/ Tegu that was used to reward old players and Patreon supporters with chat badge and access to some species.
On Bay code, we don't have unused species that aren't OP, nor do we have chat badges(yet), so OOC color is the best thing I could think of.

## Did you test it?

Not quite yet, PR is work-in-progress. I just wanted to let other contributors see the code and possibly yell at me due to how bad it is.

## Changelog

:cl:
rscadd: Add "truster players" system. At this moment, it only grants player a slightly different OOC color.
/:cl:

2021-10-04 21:50 UTC, Cupax3 requested changes, later dismissed
There's some incorrect indentations presumably making CI fail, please fix.

2021-10-04 21:50 UTC, Cupax3 commented on code/modules/goonchat/browserassets/css/browserOutput.css
> +.ooc .trusted_player		{color: #5395ff;}
Incorrect indentation pls fix

2021-10-04 21:50 UTC, Cupax3 commented on code/modules/goonchat/browserassets/css/browserOutput_white.css
> +.ooc .trusted_player		{color: #0071b8;}
Incorrect indentation pls fix

2021-10-08 17:21 UTC, Cupax3 reviewed
This would result in changes of behavior that aren't intended, I believe. Please address.

2021-10-08 17:21 UTC, Cupax3 commented on code/datums/communication/ooc.dm
> +		ooc_style = "trusted_player"
This will cause Developers to be labeled as Admins since they possess R_ADMIN and R_DEBUG.

2021-10-08 17:21 UTC, Cupax3 commented on code/modules/trusted-players/procs.dm
> +/proc/load_trusted_players()
I seem to recall that Baycode possesses a proc which can do file->list conversion, related to the whitelist systems.

2021-10-08 18:13 UTC, Shadowtail117 commented on code/datums/communication/ooc.dm
> +		ooc_style = "trusted_player"
Outside of the scope of the PR but this method of setting the style is a bit funky to begin with and could probably be moved to a flag on each role about its position. (e.g. trialmins and admins having an `F_ADMIN` (for Flag) and devs having `F_DEV`, etc.)

2021-10-08 18:25 UTC, EgorDinamit commented on code/modules/trusted-players/procs.dm
> +/proc/load_trusted_players()
Please tell if there is such a proc and where is it located.
What I have here works just fine though.

2021-10-08 18:26 UTC, EgorDinamit commented on code/datums/communication/ooc.dm
> +		ooc_style = "trusted_player"
This is only a default OOC color. I don't think that's a big issue, especially if developers have admin access, which would allow them to set their own custom OOC color.

2021-10-09 15:55 UTC, Cupax3 commented
This is good to test-merge by virtue of there being room for improvement before a full merge.

2021-10-12 20:47 UTC, Cupax3 commented
Would you be able to make the search-for-entry-in-file function generic enough that it could become a helper proc?

2021-10-12 21:16 UTC, EgorDinamit commented
> Would you be able to make the search-for-entry-in-file function generic enough that it could become a helper proc?

Done.

2021-10-12 21:16 UTC, Cupax3 approved these changes
Should be good enough.

2021-10-13 08:32 UTC, merged