Quick-equip now works for backpacks/storage items.
vlggms/tegustation-bay12 pull request #157
Opened 2021-10-17 12:42 UTC by EgorDinamit

## About the Pull Request

If you press E(quick-equip) and the active item does not have an empty slot for it - it will attempt to be put inside of a backpack.
If that fails - it will search for a storage item within a backpack, like box. If that fails too - it will be put into any other storage item on you, like belt.

## Why It's Good For The Game

Better. Faster.

It's easier to put items into your storage space now, especially if there is a lot of them.

## Did you test it?

Yes, had to test it few times until I got it working.

## Changelog

:cl:
rscadd: Quick-equip hotkey (E) now can put items inside of a backpack or any other storage item.
/:cl:

2021-10-19 20:53 UTC, Cupax3 requested changes
Could we add appropriate sounds or just the backpack sounds for these?
A sound indicator of something happening would be neat.

2021-10-19 20:53 UTC, Cupax3 commented on code/modules/mob/inventory.dm
> +				return TRUE
Any idea if we have a sound for this?

2021-10-19 20:53 UTC, Cupax3 commented on code/modules/mob/inventory.dm
> +			return TRUE
See above

2021-10-20 07:13 UTC, EgorDinamit commented on code/modules/mob/inventory.dm
> +				return TRUE
There is no sound for this. Boxes, afaik, don't have the use sound, only that zipper sound when opening.

2021-10-30 17:14 UTC, Cupax3 commented on code/modules/mob/inventory.dm
> +				return TRUE
Could you add that sound then?

2021-10-31 19:16 UTC, Cupax3 approved these changes
LGTM

2021-10-31 19:25 UTC, merged