Adds Meralyne, anti-brute chemical
vlggms/tegustation-bay12 pull request #219
Opened 2021-12-08 09:05 UTC by EgorDinamit

## About the Pull Request

Took idea from this PR: tgstation/TerraGov-Marine-Corps/pull/384

Adds Meralyne, a "tier 2" brute damage healing chemical, upgrade from bicaridine.

## Why It's Good For The Game

Most chemicals already had "tier 2s": Kelotane has Dermaline, Dexalin has "plus" version and so on.
Only bicaridine had none, so now it does. The recipe isn't easier than that of Dermaline.

## Did you test it?

No need to.

## Changelog

:cl:
rscadd: Meralyne reagent is added, a chemical effective at healing brute damage. The recipe is Bicaridine, Invaprovaline, and Iron.
/:cl:

2021-12-08 19:16 UTC, Shadowtail117 requested changes, later dismissed
Not very big on the name since most chemicals end in either -ine or -ene, and "Meralyne" sounds too much like a name than a chemical. Also, if it is meant to be a "concentrated" form of bicaridine, you might want to just label it that.

Also don't forget to add painkilling effects if you intend for it to be analgesic.

2021-12-09 07:59 UTC, EgorDinamit commented
Updated name and description, since it was such a big concern.
And no, it isn't meant to have painkilling abilities, it is simply a "tier 2" of bicaridine, the same thing dermaline is to kelotane.

2021-12-10 21:19 UTC, Shadowtail117 commented
https://github.com/vlggms/tegustation-bay12/blob/0a0cdca3c5ae0f64acb163fb1ab5ecd956ea3850/code/modules/reagents/Chemistry-Reagents/medicines/medicines_core.dm#L33-L36

Bicaridine is analgesic which is why I brought it up.

2021-12-10 21:19 UTC, Shadowtail117 requested changes, later dismissed

2021-12-10 21:19 UTC, Shadowtail117 commented on code/modules/reagents/Chemistry-Reagents/medicines/medicines_core.dm
> +	description = "Meraline is an advanced medicine used for brute medication. Works twice as good as bicaridine."
"Brute" isn't really used in the context of injuries IC.
```suggestion
	description = "Meraline is an advanced medicine used for severe physical trauma. Works twice as good as bicaridine."
```

2021-12-11 10:33 UTC, EgorDinamit commented
Updated description.
As I said earlier - no, meraline isn't supposed to have painkilling properties simply because it'd make bica-mera combo a bit too strong.

2021-12-17 21:45 UTC, Shadowtail117 approved these changes

2021-12-20 08:02 UTC, merged