Brings back fleet jackets, polos, et cetera
vlggms/tegustation-bay12 pull request #41
Opened 2021-06-23 23:50 UTC by OriginalNaym

Did not test anything, I don't even know if the changelog works properly.  Long live the utility jacket
:cl:rscadd Readds Alternative Fleet Utility Uniform Items to the uniform vendor
/:cl:

2021-06-24 00:02 UTC, Cupax3 commented
Heyo, please follow the PR template.

2021-06-24 00:04 UTC, Cupax3 requested changes
Please adjust your changed files to be in the correct format, thank you.

2021-06-24 00:04 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +	utility_extra = list(/obj/item/clothing/under/solgov/utility/fleet/officer/command,
This entire section of indentation is incorrect and one too far, not to mention you have stuff on the same line as the opening and closing parenthesis. Please fix.

2021-06-24 00:04 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +	utility_extra = list(/obj/item/clothing/under/solgov/utility/fleet/officer/command,
Also, this applies to all modified lists.

2021-06-24 21:27 UTC, Shadowtail117 requested changes

2021-06-24 21:27 UTC, Shadowtail117 commented on maps/torch/datums/uniforms_fleet.dm
> +		utility_extra = list(/obj/item/clothing/under/solgov/utility/fleet/officer/command,
This is where the checks fail (line 308). Inconsistent indentation leads to a compilation error.

2021-06-29 13:56 UTC, Cupax3 commented
This will be marked as Stale in 1 day.

2021-06-30 15:46 UTC, Cupax3 commented
@OriginalNaym Heyho, your PR is now marked as **Stale**. If you do not reply within 14 days, it will be closed. You are free to reopen it later.

2021-06-30 18:36 UTC, OriginalNaym commented
The code should be fixed now, at least it ran properly on a local server.  I'm gonna wait to see if the checks work and then change the formatting

2021-06-30 23:09 UTC, OriginalNaym commented
Formatting's fixed I think we good

2021-07-02 15:28 UTC, Ilysen commented on maps/torch/datums/uniforms_fleet.dm
> +						 /obj/item/clothing/suit/storage/jacket/solgov/fleet/command)
Is there a reason for the uh, super intense indentation? This seems to be something occurring throughout the file. If there's no reason for it, I'd request you tone it down a little and being it more in line with other formatting.

2021-07-02 15:29 UTC, Ilysen commented
The code *looks* workable, but the indentation's a little crazy, like I mentioned. I can't speak on the content because I play almost exclusively contractor and I don't know how dress uniforms are, so you'd best have someone else comment on that front.

2021-07-02 19:08 UTC, OriginalNaym commented
Just fixed the indentation back to what it was before.  Honestly, I think it'd be possible just to put the whole list on one line like dress extras do, but I'm not gonna at least for now because I'm not all that confident with what I'm doing yet and I know the list as it stands works.

Content wise: This stuff might have not been exactly what it was modeled after when Bay first introduced these parts, but there's some uniforms irl that are sort of like these

The jacket: similar to [this](https://i.gyazo.com/a46f3f95201534f4ea867d5dec53b60a.png) fleece liner the US Army uses
Polo and pants: similar to [this](https://upload.wikimedia.org/wikipedia/commons/8/8c/Web_060714-N-8629M-163_Training.jpg) version of the naval combat uniform Canada uses

2021-07-02 19:11 UTC, Cupax3 commented
> Just fixed the indentation back to what it was before. Honestly, I think it'd be possible just to put the whole list on one line like dress extras do, but I'm not gonna at least for now because I'm not all that confident with what I'm doing yet and I know the list as it stands works.
> 
> Content wise: This stuff might have not been exactly what it was modeled after when Bay first introduced these parts, but there's some uniforms irl that are sort of like these
> 
> The jacket: similar to [this](https://i.gyazo.com/a46f3f95201534f4ea867d5dec53b60a.png) fleece liner the US Army uses
> Polo and pants: similar to [this](https://upload.wikimedia.org/wikipedia/commons/8/8c/Web_060714-N-8629M-163_Training.jpg) version of the naval combat uniform Canada uses

Gonna mention it here, but please direct your attention to Discord when able - your changes have some readability and convention issues. This is DNM until addressed.

2021-07-02 19:35 UTC, Cupax3 requested changes
This PR includes

1. Undocumented edits
2. Generally poor edits, although likely via automated systems
3. Removals which are not documented

I stopped commenting the cases mid-way through because at this point these have become comments on all changes made. Please address them all and resolve the comment conversations before requesting a review again.
If you need help, ping me on Discord.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +				 /obj/item/clothing/suit/storage/jacket/solgov/fleet/command)
Please put the closing bracket on a new line.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +	dress_extra = list(/obj/item/material/sword/replica/officersword, /obj/item/clothing/head/beret/solgov/fleet/dress/command)
Please revert this.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +				 /obj/item/clothing/suit/storage/jacket/solgov/fleet)
Same as for +7 to +13

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +				 /obj/item/clothing/under/solgov/utility/fleet/polopants/command,
These leading spaces are incorrect, please fix.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> -	dress_hat = /obj/item/clothing/head/solgov/dress/fleet
Why was the NCO cap removed for engi NCO?

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +	dress_extra = list(/obj/item/material/sword/replica/officersword/pettyofficer, /obj/item/clothing/head/beret/solgov/fleet/dress)
Same as for +20

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +				 /obj/item/clothing/suit/storage/jacket/solgov/fleet)
See other comments.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +	dress_extra = list(/obj/item/material/sword/replica/officersword, /obj/item/clothing/head/beret/solgov/fleet/dress/command)
See other comments.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> -	utility_under = /obj/item/clothing/under/solgov/utility/fleet/security
Why was this moved in position to +119?

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +				 /obj/item/clothing/suit/storage/jacket/solgov/fleet/security)
See other comments.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> -
Why was this removed?

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> -	dress_hat = /obj/item/clothing/head/solgov/dress/fleet
Why was this removed?

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +	dress_extra = list(/obj/item/material/sword/replica/officersword/pettyofficer, /obj/item/clothing/head/beret/solgov/fleet/dress)
See other comments.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +				 /obj/item/clothing/suit/storage/jacket/solgov/fleet/security)
See other comments.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> +				 /obj/item/clothing/suit/storage/jacket/solgov/fleet/security)
This also removes a following empty line.

2021-07-02 19:35 UTC, Cupax3 commented on maps/torch/datums/uniforms_fleet.dm
> -	utility_under = /obj/item/clothing/under/solgov/utility/fleet/medical
Why was this moved?

2021-07-02 19:44 UTC, OriginalNaym commented
I think I'm gonna re-do this manually because I copied a lot of old baycode that included whatever another codebase needed to make it work, which is probably why so much stuff is out of place.

So this is closed, I'll try to have a new one up either today or tomorrow

2021-07-02 19:44 UTC, closed without merging