Admin restart button
vlggms/tegustation-bay12 pull request #46
Opened 2021-06-25 05:36 UTC by SkyCinnamon

## About the Pull Request

Allows admins a way to restart rounds while showing credits

port from [bay](https://github.com/Baystation12/Baystation12/pull/30808) with permission from original author

## Why It's Good For The Game

We need to give the power to the players. with this PR the 1984 admins will have no power in the ways of instant shut downs. for too long have gamers been oppressed.  We **deserve** to see those credit scenes after the SM blows up and a voted end round occurs. 

## Did you test it?

Hell yeah brother!

## Changelog

:cl: MuckerMayhem
* admin: allows admins a button to end the round while still showing credit scene
/:cl:

2021-06-25 20:31 UTC, MitztheKat commented
godspeed.

2021-06-26 05:37 UTC, Shadowtail117 requested changes
Minor grammatical changes. Also, the changelog needs reformatting. Given you've changed a bit of the wording, I suggest:

🆑 MuckerMayhem and Sky
admin: adds a button to end the round while still showing the credits
/🆑

edit: changed wording

2021-06-26 05:37 UTC, Shadowtail117 commented on code/modules/admin/admin.dm
> +		to_chat(usr,FONT_LARGE(SPAN_WARNING("You cannot end the round before its begun!")))
```suggestion
		to_chat(usr,FONT_LARGE(SPAN_WARNING("You cannot end the round before it's begun!")))
```

2021-06-26 05:37 UTC, Shadowtail117 commented on code/modules/admin/admin.dm
> +	var/check = alert("This will immediatley end the round. You sure about this?", "End Game", "Yes", "No") == "Yes"
```suggestion
	var/check = alert("This will immediately end the round. Are you sure about this?", "End Game", "Yes", "No") == "Yes"
```

2021-06-26 05:49 UTC, Shadowtail117 approved these changes

2021-06-26 05:49 UTC, Shadowtail117 commented on code/modules/admin/admin.dm
> +	set desc = "round goes bye bye"
No concerns about this, although other people might. We perform an infinitesimal amount of mischief.

2021-06-27 19:24 UTC, merged