Adds sprite shifting
vlggms/tegustation-bay12 pull request #58
Opened 2021-06-30 17:40 UTC by Shadowtail117

## About the Pull Request

Original PR is https://github.com/Baystation12/Baystation12/pull/30367. I have received permission from Shadow to use their code.

This PR allows mobs to shift their location on a single tile up to 8 pixels in any direction. Useful mostly for roleplaying, e.g., leaning against a wall or a hug or whatever.

Any form of movement, being buckled, or being grabbed will reset your sprite back to the center.

## Why It's Good For The Game

Allows for more freedom of expression during roleplaying.

## Did you test it?

Yes.

## Changelog

:cl:
rscadd: You can now shift your location on a tile up to 8 pixels in any direction using control + shift + an arrow key.
/:cl:

2021-06-30 18:07 UTC, Cupax3 requested changes
Try fixing that line, maybe the checks will stop screaming after

2021-06-30 18:07 UTC, Cupax3 commented on interface/skin.dmf
> +		elem
Bad indentation I think

2021-06-30 19:55 UTC, Shadowtail117 commented on interface/skin.dmf
> +		elem
Oops

2021-07-25 20:00 UTC, Cupax3 commented
Sqosh pls

2021-07-25 20:01 UTC, Ilysen commented
I did forget to leave a comment on this, but I do share the same concerns that were brought up in the Bay iteration of this PR. Do you have any ways that you plan to address this, either through code or policy?

2021-07-25 20:02 UTC, Shadowtail117 commented
> I did forget to leave a comment on this, but I do share the same concerns that were brought up in the Bay iteration of this PR. Do you have any ways that you plan to address this, either through code or policy?

Apologies, I didn't mention it. The threshold has been halved compared to the original iteration, so you can not be at most a quarter tile away from the center and not a half-tile. Should eliminate ambiguity.

2021-07-25 20:05 UTC, Shadowtail117 commented
squooomsh

2021-07-25 20:21 UTC, Cupax3 approved these changes
LGTM code-wise, gameplay will have to be simply tested.

2021-07-27 20:34 UTC, merged