Change skill define names to be accurate
vlggms/tegustation-bay12 pull request #79
Opened 2021-08-04 21:41 UTC by Shadowtail117

## About the Pull Request

Changes the defines for:
- `SKILL_NONE` -> `SKILL_UNTRAINED`
- `SKILL_ADEPT` -> `SKILL_TRAINED`
- `SKILL_EXPERT` -> `SKILL_EXPERIENCED`
- `SKILL_PROF` -> `SKILL_MASTER`

This has no impact on front-end.

## Why It's Good For The Game

Easier to know what skill means what.

## Did you test it?

Compiles just fine.

## Changelog

N/A

2021-08-04 21:44 UTC, Ilysen commented
Guessing this was just a simple find/replace. Fine by me, but deferring to @Cupax3 for final choice.

2021-08-04 21:46 UTC, Shadowtail117 commented
Correct guess. (After all, can't change the defines without changing where they're used.)

2021-08-04 22:46 UTC, Cupax3 submitted a review, later dismissed
Scream test via testmerge authorized

2021-08-09 09:19 UTC, Ilysen requested changes

2021-08-09 09:19 UTC, Ilysen commented on code/__defines/skills.dm
> +#define HAS_PERK       SKILL_UNTRAINED + 1
This has been in for a hot minute, but I haven't noticed any problems, nor heard anything reported. I think this is good to go. Could you make the indentation on these uniform (similar to the old defines) for consistency? After that, I think I'm good signing off on this.

2021-08-11 06:52 UTC, Cupax3 commented
I've not heard screaming, so it probably works fine. @Shadowtail117 please address the open conversation for merging.

2021-08-12 07:36 UTC, Shadowtail117 commented
Donezo

2021-08-14 06:25 UTC, Ilysen approved these changes
![](https://cdn.discordapp.com/attachments/506781129827942403/807086722005336144/Es52oMUUYAEMxyN.png)

2021-08-14 06:27 UTC, merged