species loadout adjustments + under layer for adherents
vlggms/tegustation-bay12 pull request #84
Opened 2021-08-09 02:37 UTC by Ilysen

## About the Pull Request

This makes a few adjustments to the loadout screen, although all of them are cosmetic from the front-end. More stuff has happened back-end!

### User-facing changes

* Loadout items that have species requirements now show the names for each species that can use it. Any species on this list is valid, which is indicated by the list mentioning "X or Y", and so on.
* Since loadout items now explicitly indicate which species can wear them, extraneous text in loadout item names has been clipped. `gear harness (Full Body Prosthetic, Diona, Giant Armoured Serpentid)` now just displays as `gear harness`, for example.
* Examine texts for certain species (GAS, adherents...) now appears below their worn clothing in (usually) blue italics text, instead of at the top, typically with no font styling.
* **IMPORTANT:** Adherents now have a uniform layer. Adherents can't equip a belt or an ID without a uniform! They can, obviously, still carry them around.
* Adherents now have two pocket slots.
* Adherents can now equip the gear harness from the Xenowear category, and can wear it in their uniform slot. This also opens up uniform accessories like webbing, and so on. Sprites were added to adherents for these to show up - they're strapped over the torso, under the arms, and don't extend past the waist.

### Other backend changes

<details><summary>Collapsible</summary>

* Documented all of the variables in `/datum/gear`.
* As mentioned in the user-facing changes section, species-whitelisted loadout items now explicitly show what species can use them, instead of simply failing to spawn.
</details>

## Why It's Good For The Game

This stuff is subjective, so bear with me!

Adherents are, right now, the only species in the Torch that can't equip any jumpsuit-slot item. This means they can't use suit sensors, have very limited storage space, and generally can feel clunky to play due to how little ability they have to equip any kind of gear.

Gear harnesses are deliberately adjustable and very freeform, so giving them to adherents felt like a natural fit. It's my hope that they could feel more natural with the ability to have suit sensors monitoring and the same storage capacity that other species have (even GAS!) The code automatically makes them lose the ability to equip an ID and belt without a uniform thanks to the new slot, but I felt like this made sense within the purview of every other species having that behavior, too.

Since this is a change to a species with no current maintainer, I'm flagging @Samuuu3 as a reviewer here, to get their input both from a fluff perspective and a mechanical perspective.

I'm open to hold discussion on pretty much everything in this PR.

## Did you test it?

Yep! Loadout selections correctly spawn for adherents; accessories such as drop pouches correctly attach and can be used. Examine texts for Adherents and GAS also work, although I didn't test it on the Prometheans because they're currently unused.

## Media

<details><summary>Examine text for floating adherents</summary>

![dreamseeker_uf72WONgmC](https://user-images.githubusercontent.com/47678781/128655050-56bcc911-a6c9-4716-87f5-2ae8d21269a9.png)
</details>

<details><summary>Gear harness on adherents (a bit hard to see)</summary>

![dreamseeker_Tmank8VqJf](https://user-images.githubusercontent.com/47678781/128655073-04884110-3b16-44ad-a27f-080623541db1.png)
</details>

<details><summary>Showcase of the loadout screen</summary>

![UDMCgHSPNU](https://user-images.githubusercontent.com/47678781/128655086-8b6113d1-1230-41f6-8722-b2f254a7c161.png)
</details>

<details><summary>New adherent UI, with clothing items extended. This can be easily extended in the future with unique exowear and such</summary>

![dreamseeker_mP5odGYlTA](https://user-images.githubusercontent.com/47678781/128655091-352bfe02-37c3-49c3-8c41-5962f41a65b9.png)
</details>

## Changelog

:cl:
rscadd: Items in Xenowear now list the names of each species that can equip them.
tweak: Special examine texts for species now appear below their clothing information, instead of being at the top of the message, and are italicized for clarity.
tweak: Adherents now have a uniform layer, which they need to equip an ID and a belt. They also get pockets now, as a result.
tweak: Adherents can now equip the gear harness, and pick it as a loadout item in Xenowear.
/:cl:

2021-08-09 02:41 UTC, Shadowtail117 requested changes, later dismissed
Just some stylistic requests:

- If you could add a space between what a person has equipped and any visual modifiers (for example, the "floating on a cloud of shimmering dust" for adherents), it would help make it more readable. Otherwise it's a big block of text that's harder to read.
- If possible, can you make species restrictions on a new line compared to on the same line as job restrictions?

2021-08-09 03:22 UTC, Samuuu3 approved these changes

2021-08-11 09:30 UTC, Ilysen commented
Played a full round with this as an adherent, and I didn't encounter any bugs or other stuff. Cups confirmed no runtimes. This is probably good, code-wise.

However, Shadow's stylistic concerns are still present. We discussed this in Discord and none of us were able to come to a full conclusion on how to change it. Unsure how to proceed from here.

2021-08-16 00:03 UTC, Cupax3 approved these changes
Passed scream test, the voiced stylistic concerns will be addressed in a larger scope PR soon:tm:.

2021-08-16 00:04 UTC, merged